### ISSUE TITLE
Alternate method: arrow functions to shorten constructor

### ISSUE THREAD

**Issue by aminamos** [alishahwee/simple-calculator#1]
Referring to: https://github.com/alishahwee/simple-calculator/blob/4dd3f383f04a8b285e289c307b64420f700689f5/src/components/Calculator.js#L14

I haven't used React in a while, but I think you can avoid binding `this` in the constructor by using arrow function syntax. So instead of 
```javascript
updateLastButtonPressed(key) {
    this.setState({ lastButtonPressed: key });
  }
```

Declare the function with
```javascript
updateLastButtonPressed = key => {
    this.setState({ lastButtonPressed: key });
}
```

Then line 14 could be removed entirely. Details in first section here: https://reactjs.org/docs/handling-events.html

**Comment by alishahwee** [comment]
Hi Amin!

I really appreciate the feedback! I plan on incoporating what you described in my future projects actually. I'm trying to get familiar with the traditional way to do React before moving on to more modern methods like the use of ES6 syntax like arrow functions, class field delcarations, and React hooks. 

If there's any other feedback, I'd love to hear it. Thanks again!
